// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppCommon: typeof import('./src/components/protal/components/appCommon.vue')['default']
    AppMarket: typeof import('./src/components/protal/components/appMarket.vue')['default']
    DiyButton: typeof import('./src/components/diyButton/index.vue')['default']
    DiySearch: typeof import('./src/components/diySearch/index.vue')['default']
    DiyTable: typeof import('./src/components/diyTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    Head: typeof import('./src/components/protal/components/head.vue')['default']
    HeadImg: typeof import('./src/components/headImg.vue')['default']
    Invitate: typeof import('./src/components/protal/components/invitate.vue')['default']
    List: typeof import('./src/components/pay/list.vue')['default']
    ManageSystem: typeof import('./src/components/protal/components/manageSystem.vue')['default']
    MarketCard: typeof import('./src/components/marketCard/index.vue')['default']
    Organization: typeof import('./src/components/protal/components/organization.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    Pay: typeof import('./src/components/pay/pay.vue')['default']
    Protal: typeof import('./src/components/protal/index.vue')['default']
    QrCode: typeof import('./src/components/qrCode/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SandBox: typeof import('./src/components/sandBox/index.vue')['default']
    SearchGroupPerson: typeof import('./src/components/searchs/searchGroupPerson.vue')['default']
    Searchs: typeof import('./src/components/searchs/index.vue')['default']
    SvgIcon: typeof import('./src/components/global/SvgIcon/index.vue')['default']
  }
}
